/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Formularios;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diego
 */
public class Frm_emitirFactura_CMI_V_1_3_1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Frm_emitirFactura_CMI_V_1_3_1
     */
    public Frm_emitirFactura_CMI_V_1_3_1() {
        initComponents();
        mtd_encabezadoDetalles();
        mtd_encabezadoFacturas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab_facturas = new javax.swing.JTable();
        txt_subtotal = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_fechaEmision = new org.jdesktop.swingx.JXDatePicker();
        txt_total = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_descuento = new javax.swing.JComboBox<>();
        txt_identificacion = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        txt_cantidad = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_servicio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_detalles = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_numFact = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_nombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_apellidos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 247, 248));
        setClosable(true);
        setForeground(new java.awt.Color(66, 66, 66));
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(1280, 680));
        setPreferredSize(new java.awt.Dimension(1280, 680));

        jButton2.setBackground(new java.awt.Color(0, 150, 136));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_Fondos/edit.png"))); // NOI18N
        jButton2.setText("Editar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setBackground(new java.awt.Color(0, 150, 136));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_Fondos/bin.png"))); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setBackground(new java.awt.Color(0, 150, 136));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_Fondos/bin.png"))); // NOI18N
        jButton4.setText("Eliminar");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setBackground(new java.awt.Color(0, 150, 136));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_Fondos/more.png"))); // NOI18N
        jButton5.setText("Agregar");
        jButton5.setPreferredSize(new java.awt.Dimension(100, 25));
        jButton5.addActionListener(this::jButton5ActionPerformed);

        tab_facturas.setBackground(new java.awt.Color(255, 255, 255));
        tab_facturas.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tab_facturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tab_facturas.setSelectionBackground(new java.awt.Color(137, 190, 190));
        jScrollPane2.setViewportView(tab_facturas);

        txt_subtotal.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_subtotal.setForeground(new java.awt.Color(66, 66, 66));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(66, 66, 66));
        jLabel16.setText("Subtotal :");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(66, 66, 66));
        jLabel17.setText("Descuento :");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(66, 66, 66));
        jLabel20.setText("Total :");

        txt_fechaEmision.setForeground(new java.awt.Color(66, 66, 66));
        txt_fechaEmision.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        txt_total.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_total.setForeground(new java.awt.Color(66, 66, 66));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(66, 66, 66));
        jLabel7.setText("Cédula/Pasaporte :");

        txt_descuento.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_descuento.setForeground(new java.awt.Color(66, 66, 66));
        txt_descuento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione--", "0 ", "5", "10", "15", "20", "25", " " }));
        txt_descuento.addActionListener(this::txt_descuentoActionPerformed);

        txt_identificacion.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_identificacion.setForeground(new java.awt.Color(66, 66, 66));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(66, 66, 66));
        jLabel21.setText("%");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(66, 66, 66));
        jLabel9.setText("Precio :");

        jButton6.setBackground(new java.awt.Color(0, 150, 136));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_Fondos/search.png"))); // NOI18N
        jButton6.setText("Buscar ");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        txt_cantidad.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_cantidad.setForeground(new java.awt.Color(66, 66, 66));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(66, 66, 66));
        jLabel11.setText("Cantidad :");

        txt_precio.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_precio.setForeground(new java.awt.Color(66, 66, 66));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(66, 66, 66));
        jLabel13.setText("Servicio :");

        txt_servicio.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_servicio.setForeground(new java.awt.Color(66, 66, 66));

        tab_detalles.setBackground(new java.awt.Color(255, 255, 255));
        tab_detalles.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tab_detalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tab_detalles.setSelectionBackground(new java.awt.Color(137, 190, 190));
        jScrollPane1.setViewportView(tab_detalles);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(66, 66, 66));
        jLabel1.setText("N. Factura :");

        txt_numFact.setEditable(false);
        txt_numFact.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_numFact.setForeground(new java.awt.Color(66, 66, 66));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(66, 66, 66));
        jLabel2.setText("Nombres :");

        txt_nombres.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_nombres.setForeground(new java.awt.Color(66, 66, 66));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(66, 66, 66));
        jLabel3.setText("Apellidos :");

        txt_apellidos.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_apellidos.setForeground(new java.awt.Color(66, 66, 66));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(66, 66, 66));
        jLabel6.setText("Fecha de Emision :");

        jButton1.setBackground(new java.awt.Color(0, 150, 136));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_Fondos/more.png"))); // NOI18N
        jButton1.setText("Agregar");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 25));
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_Fondos/Encabezado_CMI.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_numFact, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_fechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(7, 7, 7)
                                            .addComponent(jLabel13))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel11)))
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_servicio, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(txt_precio)
                                    .addComponent(txt_cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addGap(55, 55, 55)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_subtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(txt_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txt_numFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(txt_fechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txt_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txt_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txt_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_descuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21))
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DefaultTableModel modeloDetalles;
    DefaultTableModel modeloFacturas;

    public void mtd_encabezadoDetalles() {
        String titulos[] = {"Servicio", "Cantidad", "Precio"};
        modeloDetalles = new DefaultTableModel(null, titulos);
        tab_detalles.setModel(modeloDetalles);
    }

    public void mtd_encabezadoFacturas() {
        String titulos[] = {"N.Factura", "Apellidos", "Nombres", "CI/Pasaporte", "Fecha de Emision", "Servicios", "Total"};
        modeloFacturas = new DefaultTableModel(null, titulos);
        tab_facturas.setModel(modeloFacturas);
    }

    public void mtd_limpiarDetalles() {
        txt_servicio.setText("");
        txt_cantidad.setText("");
        txt_precio.setText("");
        txt_subtotal.setText("");
        txt_descuento.setSelectedIndex(0);
        txt_total.setText("");
    }

    public boolean mtd_duplicadoFact() {
        boolean duplicado = false;
        for (int i = 0; i < tab_facturas.getRowCount(); i++) {
            if (txt_numFact.getText().equals(tab_facturas.getValueAt(i, 0).toString())) {
                duplicado = true;
                break;
            }
        }
        return duplicado;
    }

    private void mtd_calculosTabDet() {
    double subtotal = 0;
    int totalFilas = tab_detalles.getRowCount();

    if (totalFilas <= 0) {
        txt_subtotal.setText("0.0");
        txt_total.setText("0.0");
        return;
    }

    for (int i = 0; i < totalFilas; i++) {
        try {
            int cantidad = Integer.parseInt(tab_detalles.getValueAt(i, 1).toString().trim());
            double precio = Double.parseDouble(tab_detalles.getValueAt(i, 2).toString().trim());
            subtotal += (cantidad * precio);
        } catch (Exception e) {
        }
    }

    txt_subtotal.setText(String.valueOf(subtotal));

    try {
        double descuento = 0;
        String descSel = txt_descuento.getSelectedItem().toString().trim();
        if (!descSel.equals("--Seleccione--") && !descSel.isEmpty()) {
            descuento = Double.parseDouble(descSel);
        }
        
        double totalFinal = subtotal - (subtotal * (descuento / 100));
        txt_total.setText(String.valueOf(totalFinal));
    } catch (Exception e) {
        txt_total.setText(String.valueOf(subtotal));
    }
}



    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int filaSelec = tab_detalles.getSelectedRow();

        try {
            if (filaSelec != -1) {
                txt_servicio.setText(tab_detalles.getValueAt(filaSelec, 0).toString());
                txt_cantidad.setText(tab_detalles.getValueAt(filaSelec, 1).toString());
                txt_precio.setText(tab_detalles.getValueAt(filaSelec, 2).toString());

                mtd_calculosTabDet();

            } else {
                JOptionPane.showMessageDialog(null, "Porfavor seleccione una fila");
            }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, "Error al procesar datos");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int filasel = tab_detalles.getSelectedRow();
        if (filasel == -1) {
            JOptionPane.showMessageDialog(null, "Por favor seleccione una fila");
        } else {
            modeloDetalles = (DefaultTableModel) tab_detalles.getModel();
            modeloDetalles.removeRow(filasel);
            mtd_calculosTabDet();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int filaSelec = tab_facturas.getSelectedRow();
        Clases.Cls_emitirFactura_CMI_V_1_3_1 objeto = new Clases.Cls_emitirFactura_CMI_V_1_3_1();

        if (filaSelec != -1) {
            int opcion = javax.swing.JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar este registro?");

            if (opcion == 0) {
                String idEliminado = tab_facturas.getValueAt(filaSelec, 0).toString();
                String rutaArchivo = "ArchivosPacientes/" + idEliminado + ".txt";

                if (objeto.mtd_eliminar()) {

                    modeloFacturas = (DefaultTableModel) tab_facturas.getModel();
                    modeloFacturas.removeRow(filaSelec);
                    JOptionPane.showMessageDialog(null, "Registro: " + idEliminado + " eliminado correctamente");
                    mtd_limpiarDetalles();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor Seleccione una Fila");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int filaSel = tab_facturas.getSelectedRow();

        try {
            if (txt_apellidos.getText().trim().isEmpty()) {
                txt_apellidos.requestFocus();
                throw new IllegalArgumentException("Ingrese los Apellidos del Paciente");
            }
            if (txt_nombres.getText().trim().isEmpty()) {
                txt_nombres.requestFocus();
                throw new IllegalArgumentException("Ingrese los Nombres del Paciente");
            }
            if (txt_identificacion.getText().trim().isEmpty()) {
                txt_identificacion.requestFocus();
                throw new IllegalArgumentException("Ingrese el CI/Pasaporte del Paciente");
            }
            if (txt_fechaEmision.getDate() == null) {
                txt_fechaEmision.requestFocus();
                throw new IllegalArgumentException("Ingrese la Fecha de Emision");
            }
            if (txt_total.getText().trim().isEmpty()) {
                txt_total.requestFocus();
                throw new IllegalArgumentException("No se calculó el total");
            }

            String serviciosString = txt_servicio.getText().trim();
            if (serviciosString.isEmpty() && tab_detalles.getRowCount() > 0) {
                serviciosString = tab_detalles.getValueAt(0, 0).toString();
            } else if (serviciosString.isEmpty() && filaSel != -1) {
                serviciosString = tab_facturas.getValueAt(filaSel, 5).toString();
            }

            java.text.SimpleDateFormat formatoFecha = new java.text.SimpleDateFormat("dd/MM/yyyy");
            String fechaFormateada = formatoFecha.format(txt_fechaEmision.getDate());

            double totalReal = Double.parseDouble(txt_total.getText().trim());

            if (filaSel != -1) {
                String numFact = tab_facturas.getValueAt(filaSel, 0).toString();

                Clases.Cls_emitirFactura_CMI_V_1_3_1 objeto = new Clases.Cls_emitirFactura_CMI_V_1_3_1(
                        "",
                        fechaFormateada,
                        0.0,
                        "",
                        serviciosString,
                        "",
                        totalReal,
                        txt_identificacion.getText().trim(),
                        txt_apellidos.getText().trim(),
                        txt_nombres.getText().trim(),
                        "", "", "", "", "", ""
                );
                objeto.setFac_idInterno(numFact);
                objeto.setFac_total(totalReal);

                tab_facturas.setValueAt(txt_numFact.getText(), filaSel, 0);
                tab_facturas.setValueAt(txt_apellidos.getText(), filaSel, 1);
                tab_facturas.setValueAt(txt_nombres.getText(), filaSel, 2);
                tab_facturas.setValueAt(txt_identificacion.getText(), filaSel, 3);
                tab_facturas.setValueAt(fechaFormateada, filaSel, 4);
                tab_facturas.setValueAt(serviciosString, filaSel, 5);
                tab_facturas.setValueAt(txt_total.getText(), filaSel, 6);

                objeto.mtd_guardar();

            } else {
                Clases.Cls_emitirFactura_CMI_V_1_3_1 objeto = new Clases.Cls_emitirFactura_CMI_V_1_3_1(
                        "",
                        fechaFormateada,
                        0.0,
                        "",
                        serviciosString,
                        "",
                        totalReal,
                        txt_identificacion.getText().trim(),
                        txt_apellidos.getText().trim(),
                        txt_nombres.getText().trim(),
                        "", "", "", "", "", ""
                );

                objeto.setFac_total(totalReal);

                modeloFacturas = (DefaultTableModel) tab_facturas.getModel();
                String nuevaFila[] = {
                    objeto.getFac_idInterno(),
                    objeto.getPcs_apellidos(),
                    objeto.getPcs_nombres(),
                    objeto.getPcs_CiPasaporte(),
                    objeto.getFac_fechaEmision(),
                    serviciosString,
                    txt_total.getText()
                };
                modeloFacturas.addRow(nuevaFila);

                JOptionPane.showMessageDialog(null, "Factura emitida con éxito. Código: " + objeto.getFac_idInterno());

                modeloDetalles = (DefaultTableModel) tab_detalles.getModel();
                modeloDetalles.setRowCount(0);

                txt_nombres.setText("");
                txt_apellidos.setText("");
                txt_identificacion.setText("");
                txt_fechaEmision.setDate(null);

                objeto.mtd_guardar();
                mtd_limpiarDetalles();
            }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txt_descuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descuentoActionPerformed
        // TODO add your handling code here:
        mtd_calculosTabDet();
    }//GEN-LAST:event_txt_descuentoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Clases.Cls_emitirFactura_CMI_V_1_3_1 objeto = new Clases.Cls_emitirFactura_CMI_V_1_3_1();

        if (objeto.mtd_buscar()) {
            txt_apellidos.setText(objeto.getPcs_apellidos());
            txt_nombres.setText(objeto.getPcs_nombres());
            txt_identificacion.setText(objeto.getPcs_CiPasaporte());
            txt_numFact.setText(objeto.getFac_idInterno());

            if (objeto.getFac_fechaEmision() != null && !objeto.getFac_fechaEmision().isEmpty()) {
                try {
                    java.text.SimpleDateFormat format = new java.text.SimpleDateFormat("dd/MM/yyyy");
                    txt_fechaEmision.setDate(format.parse(objeto.getFac_fechaEmision()));
                } catch (Exception e) {
                }
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int filaSel = tab_detalles.getSelectedRow();

    try {
        String servicio = txt_servicio.getText().trim();
        String cantidad = txt_cantidad.getText().trim();
        String precioStr = txt_precio.getText().trim();

        if (servicio.isEmpty()) {
            txt_servicio.requestFocus();
            JOptionPane.showMessageDialog(null, "Ingrese el servicio");
            return;
        }
        if (cantidad.isEmpty()) {
            txt_cantidad.requestFocus();
            JOptionPane.showMessageDialog(null, "Ingrese la cantidad");
            return;
        }
        int cant = Integer.parseInt(cantidad);
        if (cant <= 0) {
            txt_cantidad.requestFocus();
            JOptionPane.showMessageDialog(null, "Ingrese una cantidad mayor a 0");
            return;
        }
        if (precioStr.isEmpty()) {
            txt_precio.requestFocus();
            JOptionPane.showMessageDialog(null, "Ingrese el precio");
            return;
        }
        double precio = Double.parseDouble(precioStr);

        modeloDetalles = (DefaultTableModel) tab_detalles.getModel();

        if (filaSel != -1) {
            tab_detalles.setValueAt(servicio, filaSel, 0);
            tab_detalles.setValueAt(cantidad, filaSel, 1);
            tab_detalles.setValueAt(String.valueOf(precio), filaSel, 2);
        } else {
            String nuevaFila[] = {servicio, cantidad, String.valueOf(precio)};
            modeloDetalles.addRow(nuevaFila);
        }

        try {
            mtd_calculosTabDet();
        } catch (Exception e) {
            System.err.println("Error omitido en calculos: " + e.getMessage());
        }

        try {
            mtd_limpiarDetalles();
        } catch (Exception e) {
            txt_servicio.setText("");
            txt_cantidad.setText("");
            txt_precio.setText("");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Porfavor ingrese un número valido");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error general: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tab_detalles;
    private javax.swing.JTable tab_facturas;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JComboBox<String> txt_descuento;
    private org.jdesktop.swingx.JXDatePicker txt_fechaEmision;
    private javax.swing.JTextField txt_identificacion;
    private javax.swing.JTextField txt_nombres;
    private javax.swing.JTextField txt_numFact;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_servicio;
    private javax.swing.JTextField txt_subtotal;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
