/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Formularios;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diego
 */
public class Frm_consultaLabs_V1_3_1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Frm_consultaLabs_V1_3_1
     */
    public Frm_consultaLabs_V1_3_1() {
        initComponents();
        mtd_encabezado();
        mtd_cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_idInterno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_ruc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_nombComer = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_contactoPrinc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_numContact = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_sucursal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_consulLabs = new javax.swing.JTable();

        setBackground(new java.awt.Color(245, 247, 248));
        setMinimumSize(new java.awt.Dimension(1280, 680));
        setPreferredSize(new java.awt.Dimension(1280, 680));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 150, 136));
        jLabel2.setText("Base de Datos");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(66, 66, 66));
        jLabel3.setText("ID Interno :");

        txt_idInterno.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_idInterno.setForeground(new java.awt.Color(66, 66, 66));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(66, 66, 66));
        jLabel1.setText("RUC/Registro Sanitario :");

        txt_ruc.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_ruc.setForeground(new java.awt.Color(66, 66, 66));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(66, 66, 66));
        jLabel4.setText("Nombre Comercial :");

        txt_nombComer.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_nombComer.setForeground(new java.awt.Color(66, 66, 66));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(66, 66, 66));
        jLabel5.setText("Contacto Principal :");

        txt_contactoPrinc.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_contactoPrinc.setForeground(new java.awt.Color(66, 66, 66));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(66, 66, 66));
        jLabel6.setText("Número de Contacto :");

        txt_numContact.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_numContact.setForeground(new java.awt.Color(66, 66, 66));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(66, 66, 66));
        jLabel7.setText("E-Mail :");

        txt_correo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_correo.setForeground(new java.awt.Color(66, 66, 66));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(66, 66, 66));
        jLabel8.setText("Sucursal :");

        txt_sucursal.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_sucursal.setForeground(new java.awt.Color(66, 66, 66));

        jButton1.setBackground(new java.awt.Color(0, 150, 136));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton1.setText("Actualizar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(0, 150, 136));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton2.setText("Editar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setBackground(new java.awt.Color(0, 150, 136));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setBackground(new java.awt.Color(0, 150, 136));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton4.setText("Buscar");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        tab_consulLabs.setBackground(new java.awt.Color(255, 255, 255));
        tab_consulLabs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tab_consulLabs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(574, 574, 574)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_idInterno)
                            .addComponent(txt_ruc)
                            .addComponent(txt_nombComer)
                            .addComponent(txt_contactoPrinc)
                            .addComponent(txt_numContact)
                            .addComponent(txt_correo)
                            .addComponent(txt_sucursal, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_idInterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_ruc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_nombComer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_contactoPrinc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_numContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DefaultTableModel modelo;
    Clases.Cls_registroLaboratorios_V1_3_1 objeto1 = new Clases.Cls_registroLaboratorios_V1_3_1();

    private void mtd_cargarTabla() {
        Clases.Cls_consultaLabs_V1_3_1.mtd_cargarDatosA_Modelo((DefaultTableModel) tab_consulLabs.getModel());
    }

    public void mtd_encabezado() {
        String titulos[] = {"ID", "RUC/Registro Sanitario", "Nombre Comercial", "Contacto Principal", "Número de Contacto", "E-Mail", "Sucursal"};
        modelo = new DefaultTableModel(null, titulos);
        tab_consulLabs.setModel(modelo);
    }

    public void mtd_limpieza() {
        txt_idInterno.setText("");
        txt_ruc.setText("");
        txt_nombComer.setText("");
        txt_contactoPrinc.setText("");
        txt_numContact.setText("");
        txt_correo.setText("");
        txt_sucursal.setText("");
    }

    public boolean mtd_duplicado() {
        boolean duplicado = false;
        for (int i = 0; i < tab_consulLabs.getRowCount(); i++) {
            if (txt_ruc.getText().equals(tab_consulLabs.getValueAt(i, 1).toString()) || txt_idInterno.getText().equals(tab_consulLabs.getValueAt(i, 0).toString())) {
                duplicado = true;
                break;
            }
        }
        return duplicado;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int filaSel = tab_consulLabs.getSelectedRow();
        try {
            if (txt_ruc.getText().trim().isEmpty()) {
                txt_ruc.requestFocus();
                throw new IllegalArgumentException("Ingrese el RUC/Registro Sanitario");
            }
            if (txt_nombComer.getText().trim().isEmpty()) {
                txt_nombComer.requestFocus();
                throw new IllegalArgumentException("Ingrese el Nombre Comercial");
            }
            if (txt_contactoPrinc.getText().trim().isEmpty()) {
                txt_contactoPrinc.requestFocus();
                throw new IllegalArgumentException("Ingrese el Nombre del Contacto Principal");
            }
            if (txt_numContact.getText().trim().isEmpty()) {
                txt_numContact.requestFocus();
                throw new IllegalArgumentException("Ingrese el Número del Contacto Principal");
            }
            if (txt_correo.getText().trim().isEmpty()) {
                txt_correo.requestFocus();
                throw new IllegalArgumentException("Ingrese el Correo Electronico");
            }
            if (txt_sucursal.getText().trim().isEmpty()) {
                txt_sucursal.requestFocus();
                throw new IllegalArgumentException("Ingrese la Dirección de la Sucursal");
            }

            if (filaSel != -1) {
                String idInterno = tab_consulLabs.getValueAt(filaSel, 0).toString();

                Clases.Cls_registroLaboratorios_V1_3_1 objetoActualizar = new Clases.Cls_registroLaboratorios_V1_3_1(idInterno, txt_ruc.getText(), txt_nombComer.getText(), txt_contactoPrinc.getText(), txt_numContact.getText(), txt_correo.getText(), txt_sucursal.getText());
                tab_consulLabs.setValueAt(txt_ruc.getText(), filaSel, 1);
                tab_consulLabs.setValueAt(txt_nombComer.getText(), filaSel, 2);
                tab_consulLabs.setValueAt(txt_contactoPrinc.getText(), filaSel, 3);
                tab_consulLabs.setValueAt(txt_numContact.getText(), filaSel, 4);
                tab_consulLabs.setValueAt(txt_correo.getText(), filaSel, 5);
                tab_consulLabs.setValueAt(txt_sucursal.getText(), filaSel, 6);

                if (objetoActualizar.mtd_guardar()) {
                    JOptionPane.showMessageDialog(null, "Registro Actualizado Correctamente");
                    mtd_limpieza();
                }
            } else {
                Clases.Cls_registroLaboratorios_V1_3_1 objeto = new Clases.Cls_registroLaboratorios_V1_3_1(txt_ruc.getText(), txt_nombComer.getText(), txt_contactoPrinc.getText(), txt_numContact.getText(), txt_correo.getText(), txt_sucursal.getText());
                modelo = (DefaultTableModel) tab_consulLabs.getModel();
                String nuevaFila[] = {objeto.getLb_idInterno(), objeto.getLb_ruc(), objeto.getLb_nombreComercal(), objeto.getLb_contactoPrincipal(), objeto.getLb_numContactoPrinci(), objeto.getLb_correo(), objeto.getLb_sucursal()};
                modelo.addRow(nuevaFila);
                JOptionPane.showMessageDialog(null, "Registro : " + objeto.getLb_idInterno() + " Cargado Correctamente");
                JOptionPane.showMessageDialog(null, "Verifique los Datos antes de Guardarlos");
                mtd_limpieza();
            }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, "Error : Campos Incompletos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int filaSel = tab_consulLabs.getSelectedRow();
        try {
            if (filaSel != -1) {
                txt_idInterno.setText(tab_consulLabs.getValueAt(filaSel, 0).toString());
                txt_ruc.setText(tab_consulLabs.getValueAt(filaSel, 2).toString());
                txt_nombComer.setText(tab_consulLabs.getValueAt(filaSel, 3).toString());
                txt_contactoPrinc.setText(tab_consulLabs.getValueAt(filaSel, 3).toString());
                txt_numContact.setText(tab_consulLabs.getValueAt(filaSel, 4).toString());
                txt_correo.setText(tab_consulLabs.getValueAt(filaSel, 5).toString());
                txt_sucursal.setText(tab_consulLabs.getValueAt(filaSel, 6).toString());
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione una Fila");
            }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, "Error Desconocido :" + e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Clases.Cls_registroLaboratorios_V1_3_1 objeto = new Clases.Cls_registroLaboratorios_V1_3_1();
        int filaSelec = tab_consulLabs.getSelectedRow();
        if (filaSelec != -1) {
            int opcion = javax.swing.JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar este registro?");

            if (opcion == 0) {
                if (objeto.mtd_eliminar() == true) {
                    modelo = (DefaultTableModel) tab_consulLabs.getModel();
                    String idEliminado = tab_consulLabs.getValueAt(filaSelec, 0).toString();
                    modelo.removeRow(filaSelec);
                    javax.swing.JOptionPane.showMessageDialog(null, "Registro: " + idEliminado + " eliminado correctamente");
                    mtd_limpieza();
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Por favor Seleccione una Fila");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Clases.Cls_registroLaboratorios_V1_3_1 objeto = new Clases.Cls_registroLaboratorios_V1_3_1();
        objeto.setLb_idInterno(txt_idInterno.getText());
        if (objeto.mtd_buscar()) {
            modelo = (DefaultTableModel) tab_consulLabs.getModel();
            String nuevaFila[] = {
                objeto.getLb_idInterno(),
                objeto.getLb_ruc(),
                objeto.getLb_nombreComercal(),
                objeto.getLb_contactoPrincipal(),
                objeto.getLb_numContactoPrinci(),
                objeto.getLb_correo(),
                objeto.getLb_sucursal()
            };
            modelo.addRow(nuevaFila);
        }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab_consulLabs;
    private javax.swing.JTextField txt_contactoPrinc;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_idInterno;
    private javax.swing.JTextField txt_nombComer;
    private javax.swing.JTextField txt_numContact;
    private javax.swing.JTextField txt_ruc;
    private javax.swing.JTextField txt_sucursal;
    // End of variables declaration//GEN-END:variables
}
