/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Formularios;

import Clases.Cls_registroLaboratorios_V1_3_1;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diego
 */
public class Frm_registroLabs_V1_3_1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Frm_registroLabs
     */
    public Frm_registroLabs_V1_3_1() {
        initComponents();
        mtd_encabezado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_ruc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_nombComer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_contactoPrinc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_numContact = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_correoLab = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_dirLab = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_registroLabs = new javax.swing.JTable();

        setBackground(new java.awt.Color(245, 247, 248));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(1280, 680));
        setPreferredSize(new java.awt.Dimension(1280, 680));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 150, 136));
        jLabel2.setText("Registro de Laboratorios");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(66, 66, 66));
        jLabel3.setText("RUC/Registro Sanitario :");

        txt_ruc.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_ruc.setForeground(new java.awt.Color(66, 66, 66));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(66, 66, 66));
        jLabel1.setText("Nombre Comercial :");

        txt_nombComer.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_nombComer.setForeground(new java.awt.Color(66, 66, 66));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(66, 66, 66));
        jLabel4.setText("Contacto Principal :");

        txt_contactoPrinc.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_contactoPrinc.setForeground(new java.awt.Color(66, 66, 66));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(66, 66, 66));
        jLabel5.setText("Número de Contacto :");

        txt_numContact.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_numContact.setForeground(new java.awt.Color(66, 66, 66));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(66, 66, 66));
        jLabel6.setText("Correo :");

        txt_correoLab.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_correoLab.setForeground(new java.awt.Color(66, 66, 66));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(66, 66, 66));
        jLabel7.setText("Sucursal :");

        txt_dirLab.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_dirLab.setForeground(new java.awt.Color(66, 66, 66));

        jButton1.setBackground(new java.awt.Color(0, 150, 136));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_Fondos/more.png"))); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(0, 150, 136));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_Fondos/edit.png"))); // NOI18N
        jButton2.setText("Editar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setBackground(new java.awt.Color(0, 150, 136));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_Fondos/bin.png"))); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setBackground(new java.awt.Color(0, 150, 136));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_Fondos/sav (1).png"))); // NOI18N
        jButton4.setText("Guardar");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        tab_registroLabs.setBackground(new java.awt.Color(255, 255, 255));
        tab_registroLabs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tab_registroLabs.setSelectionBackground(new java.awt.Color(137, 190, 190));
        jScrollPane1.setViewportView(tab_registroLabs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(528, 528, 528)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_ruc)
                            .addComponent(txt_nombComer)
                            .addComponent(txt_contactoPrinc)
                            .addComponent(txt_numContact)
                            .addComponent(txt_correoLab)
                            .addComponent(txt_dirLab, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton3))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(95, 95, 95)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_ruc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_nombComer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_contactoPrinc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_numContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_correoLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_dirLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DefaultTableModel modelo;

    public void mtd_encabezado() {
        String titulos[] = {"ID", "RUC/Registro Sanitario", "Nombre Comercial", "Contacto Principal", "Número", "E-Mail", "Sucursal"};
        modelo = new DefaultTableModel(null, titulos);
        tab_registroLabs.setModel(modelo);
    }

    public void mtd_limpieza() {
        txt_ruc.setText("");
        txt_nombComer.setText("");
        txt_contactoPrinc.setText("");
        txt_numContact.setText("");
        txt_correoLab.setText("");
        txt_dirLab.setText("");
    }

    public boolean mtd_duplicado() {
        boolean duplicado = false;
        for (int i = 0; i < tab_registroLabs.getRowCount(); i++) {
            if (txt_ruc.getText().equals(tab_registroLabs.getValueAt(i, 1).toString())) {
                duplicado = true;
                break;
            }
        }
        return duplicado;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int filaSel = tab_registroLabs.getSelectedRow();
        try {
            if (txt_ruc.getText().trim().isEmpty()) {
                txt_ruc.requestFocus();
                throw new IllegalArgumentException("Ingrese el RUC/Registro Sanitario");
            }
            if (txt_nombComer.getText().trim().isEmpty()) {
                txt_nombComer.requestFocus();
                throw new IllegalArgumentException("Ingrese el Nombre Comercial");
            }
            if (txt_contactoPrinc.getText().trim().isEmpty()) {
                txt_contactoPrinc.requestFocus();
                throw new IllegalArgumentException("Ingrese el Nombre del Contacto Principal");
            }
            if (txt_numContact.getText().trim().isEmpty()) {
                txt_numContact.requestFocus();
                throw new IllegalArgumentException("Ingrese el Número del Contacto Principal");
            }
            if (txt_correoLab.getText().trim().isEmpty()) {
                txt_correoLab.requestFocus();
                throw new IllegalArgumentException("Ingrese la Dirección de Correo Electronico");
            }
            if (txt_dirLab.getText().trim().isEmpty()) {
                txt_correoLab.requestFocus();
                throw new IllegalArgumentException("Ingrese la Dirección de la Sucursal");
            }
            if (filaSel != -1) {
                String idInterno = tab_registroLabs.getValueAt(filaSel, 0).toString();
                tab_registroLabs.setValueAt(idInterno, filaSel, 0);
                tab_registroLabs.setValueAt(txt_ruc.getText(), filaSel, 1);
                tab_registroLabs.setValueAt(txt_nombComer.getText(), filaSel, 2);
                tab_registroLabs.setValueAt(txt_contactoPrinc.getText(), filaSel, 3);
                tab_registroLabs.setValueAt(txt_numContact.getText(), filaSel, 4);
                tab_registroLabs.setValueAt(txt_correoLab.getText(), filaSel, 5);
                tab_registroLabs.setValueAt(txt_dirLab.getText(), filaSel, 6);
                JOptionPane.showMessageDialog(null, "Registro Actualizado Correctamente");
                mtd_limpieza();
            } else {
                if (mtd_duplicado() == false) {
                    Clases.Cls_registroLaboratorios_V1_3_1 objeto = new Clases.Cls_registroLaboratorios_V1_3_1(txt_ruc.getText().trim(), txt_nombComer.getText().trim(), txt_contactoPrinc.getText().trim(), txt_numContact.getText().trim(), txt_correoLab.getText().trim(), txt_dirLab.getText().trim());
                    modelo = (DefaultTableModel) tab_registroLabs.getModel();
                    String nuevaFila[] = {objeto.getLb_idInterno(), objeto.getLb_ruc(), objeto.getLb_nombreComercal(), objeto.getLb_contactoPrincipal(), objeto.getLb_numContactoPrinci(), objeto.getLb_correo(), objeto.getLb_sucursal()};
                    modelo.addRow(nuevaFila);
                    JOptionPane.showMessageDialog(null, "Registro :" + objeto.getLb_idInterno() + " Cargado Correctamente");
                    JOptionPane.showMessageDialog(null, "Verifique los Datos antes de Guardarlos");
                    mtd_limpieza();
                }
            }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, "Error: Campos Incompletos");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Desconocido :" + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int filaSel = tab_registroLabs.getSelectedRow();
        try {
            if (filaSel != -1) {
                txt_ruc.setText(tab_registroLabs.getValueAt(filaSel, 1).toString());
                txt_nombComer.setText(tab_registroLabs.getValueAt(filaSel, 2).toString());
                txt_contactoPrinc.setText(tab_registroLabs.getValueAt(filaSel, 3).toString());
                txt_numContact.setText(tab_registroLabs.getValueAt(filaSel, 4).toString());
                txt_correoLab.setText(tab_registroLabs.getValueAt(filaSel, 5).toString());
                txt_dirLab.setText(tab_registroLabs.getValueAt(filaSel, 6).toString());
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione una Fila");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Desconocido :" + e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int filaSel = tab_registroLabs.getSelectedRow();
        try {
            if (filaSel != -1) {
                int opcion = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar este registro?");
                if (opcion == 0) {
                    modelo = (DefaultTableModel) tab_registroLabs.getModel();
                    String idEliminado = tab_registroLabs.getValueAt(filaSel, 0).toString();
                    modelo.removeRow(filaSel);
                    JOptionPane.showMessageDialog(null, "Registro :" + idEliminado + " Eliminado Correctamente");
                    mtd_limpieza();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Desconocido :" + e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int filaSel = tab_registroLabs.getSelectedRow();
        try {
            if (filaSel != -1) {
                Clases.Cls_registroLaboratorios_V1_3_1 objeto = new Cls_registroLaboratorios_V1_3_1(
                        tab_registroLabs.getValueAt(filaSel, 0).toString(),
                        tab_registroLabs.getValueAt(filaSel, 1).toString(),
                        tab_registroLabs.getValueAt(filaSel, 2).toString(),
                        tab_registroLabs.getValueAt(filaSel, 3).toString(),
                        tab_registroLabs.getValueAt(filaSel, 4).toString(),
                        tab_registroLabs.getValueAt(filaSel, 5).toString(),
                        tab_registroLabs.getValueAt(filaSel, 6).toString()
                );
                if (objeto.mtd_guardar()) {
                    JOptionPane.showMessageDialog(null, "Registro: " + objeto.getLb_idInterno() + " Guardado Exitosamente");
                    mtd_limpieza();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione una Fila");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al Guardar Datos: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab_registroLabs;
    private javax.swing.JTextField txt_contactoPrinc;
    private javax.swing.JTextField txt_correoLab;
    private javax.swing.JTextField txt_dirLab;
    private javax.swing.JTextField txt_nombComer;
    private javax.swing.JTextField txt_numContact;
    private javax.swing.JTextField txt_ruc;
    // End of variables declaration//GEN-END:variables
}
