/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Formularios;

import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diego
 */
public class Frm_registroMEDInventarios_V_1_3_1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Frm_registroMEDInventarios
     */
    public Frm_registroMEDInventarios_V_1_3_1() {
        initComponents();
        mtd_encabezado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_nombComer = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_princAct = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_lab = new javax.swing.JTextField();
        btn_Blab = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_present = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_unitDosis = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_fechaIngreso = new org.jdesktop.swingx.JXDatePicker();
        jLabel8 = new javax.swing.JLabel();
        txt_fechaVence = new org.jdesktop.swingx.JXDatePicker();
        jLabel9 = new javax.swing.JLabel();
        txt_loteInt = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txt_loteFab = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_regisMedInv = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(1280, 680));
        setPreferredSize(new java.awt.Dimension(1280, 680));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Registro de Muestras Médicas");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setText("N. Comercial :");

        txt_nombComer.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setText("Principio Activo :");

        txt_princAct.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setText("Laboratorio :");

        txt_lab.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        btn_Blab.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btn_Blab.setText("B");
        btn_Blab.addActionListener(this::btn_BlabActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setText("Presentación :");

        txt_present.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_present.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Seleccione---", "Tabletas/Cápsulas", "Ampollas", "Frasco/Jarabe", "Tubo/Crema", "Sachet/Sobre", "Dispositivo/Inhalador", " " }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setText("Unidades/Dosis :");

        txt_unitDosis.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setText("F. Ingreso :");

        txt_fechaIngreso.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setText("F. Vencimiento :");

        txt_fechaVence.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel9.setText("Lote Interno :");

        txt_loteInt.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_loteInt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Seleccione---", "Analgésicos/Antiinflamatorios", "Antibióticos", "Gastrointestinales", "Probióticos", "Respiratorios/Antihistamínicos", "Misceláneos" }));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel10.setText("Lote Fab :");

        txt_loteFab.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel11.setText("Cantidad :");

        txt_cantidad.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton2.setText("Agregar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton3.setText("Editar");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton4.setText("Eliminar");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton5.setText("Guardar");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        tab_regisMedInv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tab_regisMedInv);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(506, 506, 506)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_loteFab, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(txt_cantidad)
                                    .addComponent(txt_loteInt, 0, 1, Short.MAX_VALUE)
                                    .addComponent(txt_fechaVence, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(txt_fechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(txt_unitDosis)
                                    .addComponent(txt_present, 0, 1, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_lab, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_Blab, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                                    .addComponent(txt_princAct)
                                    .addComponent(txt_nombComer))))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_nombComer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_princAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_lab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Blab))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_present, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_unitDosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_fechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_fechaVence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_loteInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_loteFab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)
                        .addGap(0, 82, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DefaultTableModel modelo;
    Clases.Cls_registroInMED_V_1_3_1 objeto = new Clases.Cls_registroInMED_V_1_3_1();
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");

    public void mtd_limpieza() {
        txt_nombComer.setText("");
        txt_princAct.setText("");
        txt_lab.setText("");
        txt_present.setSelectedIndex(0);
        txt_unitDosis.setText("");
        txt_fechaIngreso.setDate(null);
        txt_fechaVence.setDate(null);
        txt_loteInt.setSelectedIndex(0);
        txt_loteFab.setText("");
        txt_cantidad.setText("");
    }

    public boolean mtd_duplicado() {
        boolean duplicado = false;
        String idNuevo = String.valueOf(objeto.getInMED_idInterno());

        for (int i = 0; i < tab_regisMedInv.getRowCount(); i++) {
            String idTabla = String.valueOf(tab_regisMedInv.getValueAt(i, 0));
            if (idTabla.equals(idNuevo)) {
                duplicado = true;
                break;
            }
        }
        return duplicado;
    }

    public void mtd_encabezado() {
        String titulos[] = {"ID", "N.Comercial", "P.Activo", "Laboratorio", "Presentación", "Unidades/Dosis", "F. Ingreso", "F. Vence", "Lote Int.", "Lote Fab", "Stock"};
        modelo = new DefaultTableModel(null, titulos);
        tab_regisMedInv.setModel(modelo);
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int filaSel = tab_regisMedInv.getSelectedRow();
        try {
            if (txt_nombComer.getText().trim().isEmpty()) {
                txt_nombComer.requestFocus();
                throw new IllegalArgumentException("Ingrese el Nombre Comercial");
            }
            if (txt_princAct.getText().trim().isEmpty()) {
                txt_princAct.requestFocus();
                throw new IllegalArgumentException("Ingrese el Principio Activo");
            }
            if (txt_lab.getText().trim().isEmpty()) {
                txt_lab.requestFocus();
                throw new IllegalArgumentException("Ingrese el Laboratorio de Origen");
            }
            if (txt_present.getSelectedIndex() == 0) {
                txt_present.requestFocus();
                throw new IllegalArgumentException("Seleccione el Tipo de Presentación");
            }
            if (txt_unitDosis.getText().trim().isEmpty()) {
                txt_unitDosis.requestFocus();
                throw new IllegalArgumentException("Ingrese las Unidades/Dosis");
            }
            if (txt_fechaIngreso.getDate() == null) {
                txt_fechaIngreso.requestFocus();
                throw new IllegalArgumentException("Ingrese la Fecha de Ingreso");
            }
            if (txt_fechaVence.getDate() == null) {
                txt_fechaVence.requestFocus();
                throw new IllegalArgumentException("Ingrese la Fecha de Vencimiento");
            }
            if (txt_loteInt.getSelectedIndex() == 0) {
                txt_loteInt.requestFocus();
                throw new IllegalArgumentException("Seleccione el Lote Destino");
            }
            if (txt_loteFab.getText().trim().isEmpty()) {
                txt_loteFab.requestFocus();
                throw new IllegalArgumentException("Ingrese el Lote del Fabricante");
            }
            if (txt_cantidad.getText().trim().isEmpty()) {
                txt_cantidad.requestFocus();
                throw new IllegalArgumentException("Ingrese la cantidad");
            }
            if (filaSel != -1) {
                String idExistente = tab_regisMedInv.getValueAt(filaSel, 0).toString();

                tab_regisMedInv.setValueAt(idExistente, filaSel, 0);
                tab_regisMedInv.setValueAt(txt_nombComer.getText(), filaSel, 1);
                tab_regisMedInv.setValueAt(txt_princAct.getText(), filaSel, 2);
                tab_regisMedInv.setValueAt(txt_lab.getText(), filaSel, 3);
                tab_regisMedInv.setValueAt(txt_present.getSelectedItem(), filaSel, 4);
                tab_regisMedInv.setValueAt(txt_unitDosis.getText(), filaSel, 5);
                tab_regisMedInv.setValueAt(sdf.format(txt_fechaIngreso.getDate()), filaSel, 6);
                tab_regisMedInv.setValueAt(sdf.format(txt_fechaVence.getDate()), filaSel, 7);
                tab_regisMedInv.setValueAt(txt_loteInt.getSelectedItem(), filaSel, 8);
                tab_regisMedInv.setValueAt(txt_loteFab.getText(), filaSel, 9);
                tab_regisMedInv.setValueAt(String.valueOf(txt_cantidad.getText()), filaSel, 10);
                JOptionPane.showMessageDialog(null, "Registro :" + idExistente);
                mtd_limpieza();
            } else {
                java.time.LocalDate localFechaIngreso = null;
                java.time.LocalDate localFechaVence = null;

                if (txt_fechaIngreso.getDate() != null) {
                    localFechaIngreso = txt_fechaIngreso.getDate().toInstant()
                            .atZone(java.time.ZoneId.systemDefault()).toLocalDate();
                }
                if (txt_fechaVence.getDate() != null) {
                    localFechaVence = txt_fechaVence.getDate().toInstant()
                            .atZone(java.time.ZoneId.systemDefault()).toLocalDate();
                }
                Double cantDouble = 0.0;
                try {
                    cantDouble = Double.parseDouble(txt_cantidad.getText().trim());
                } catch (NumberFormatException e) {
                }

                Clases.Cls_registroInMED_V_1_3_1 objeto1 = new Clases.Cls_registroInMED_V_1_3_1(
                        txt_nombComer.getText(),
                        txt_princAct.getText(),
                        txt_lab.getText(),
                        txt_present.getSelectedItem().toString(),
                        txt_unitDosis.getText(),
                        localFechaIngreso,
                        localFechaVence,
                        txt_loteInt.getSelectedItem().toString(),
                        txt_loteFab.getText(),
                        cantDouble
                );
                modelo = (DefaultTableModel) tab_regisMedInv.getModel();
                Object nuevaFila[] = {
                    objeto1.getInMED_idInterno(),
                    objeto1.getInMED_nombComer(),
                    objeto1.getInMED_prinAct(),
                    objeto1.getInMED_lab(),
                    objeto1.getInMED_present(),
                    objeto1.getInMED_unitDosis(),
                    sdf.format(txt_fechaIngreso.getDate()),
                    sdf.format(txt_fechaVence.getDate()),
                    objeto1.getInMed_loteInt(),
                    objeto1.getInMed_loteFab(),
                    objeto1.getInMed_cant()
                };
                modelo.addRow(nuevaFila);
                JOptionPane.showMessageDialog(null, "Registro: " + objeto1.getInMED_idInterno() + " Cargado Correctamente");
                JOptionPane.showMessageDialog(null, "Verifique los Datos antes de Guardarlos");
                mtd_limpieza();
            }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error de Validación", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int filaSel = tab_regisMedInv.getSelectedRow();
        try {
            if (filaSel != -1) {
                txt_nombComer.setText(tab_regisMedInv.getValueAt(filaSel, 1).toString());
                txt_princAct.setText(tab_regisMedInv.getValueAt(filaSel, 2).toString());
                txt_lab.setText(tab_regisMedInv.getValueAt(filaSel, 3).toString());
                txt_present.setSelectedItem(tab_regisMedInv.getValueAt(filaSel, 4).toString());
                txt_unitDosis.setText(tab_regisMedInv.getValueAt(filaSel, 5).toString());
                java.util.Date fecha = sdf.parse(tab_regisMedInv.getValueAt(filaSel, 6).toString());
                txt_fechaIngreso.setDate(fecha);
                java.util.Date fecha2 = sdf.parse(tab_regisMedInv.getValueAt(filaSel, 7).toString());
                txt_fechaVence.setDate(fecha2);
                txt_loteInt.setSelectedItem(tab_regisMedInv.getValueAt(filaSel, 8).toString());
                txt_loteFab.setText(tab_regisMedInv.getValueAt(filaSel, 9).toString());
                txt_cantidad.setText(tab_regisMedInv.getValueAt(filaSel, 10).toString());

            } else {
                JOptionPane.showMessageDialog(null, "Seleccione una Fila");
            }
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Error en el Formado de Fecha dd/mm/aaaa");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese una Cantidad Valida");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int filaSel = tab_regisMedInv.getSelectedRow();
        try {
            if (filaSel != -1) {
                int opcion = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar este registro?");
                if (opcion == 0) {
                    modelo = (DefaultTableModel) tab_regisMedInv.getModel();
                    String idEliminado = tab_regisMedInv.getValueAt(filaSel, 0).toString();
                    modelo.removeRow(filaSel);
                    JOptionPane.showMessageDialog(null, "Registro :" + idEliminado + " Eliminado Correctamente");
                    mtd_limpieza();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Desconocido :" + e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int filaSel = tab_regisMedInv.getSelectedRow();
        try {
            if (filaSel != -1) {
                Clases.Cls_registroInMED_V_1_3_1 objeto2 = new Clases.Cls_registroInMED_V_1_3_1(
                        tab_regisMedInv.getValueAt(filaSel, 0).toString(),
                        tab_regisMedInv.getValueAt(filaSel, 1).toString(),
                        tab_regisMedInv.getValueAt(filaSel, 2).toString(),
                        tab_regisMedInv.getValueAt(filaSel, 3).toString(),
                        tab_regisMedInv.getValueAt(filaSel, 4).toString(),
                        tab_regisMedInv.getValueAt(filaSel, 5).toString(),
                        java.time.LocalDate.parse(tab_regisMedInv.getValueAt(filaSel, 6).toString(), java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy")),
                        java.time.LocalDate.parse(tab_regisMedInv.getValueAt(filaSel, 7).toString(), java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy")),
                        tab_regisMedInv.getValueAt(filaSel, 8).toString(),
                        tab_regisMedInv.getValueAt(filaSel, 9).toString(),
                        Double.parseDouble(tab_regisMedInv.getValueAt(filaSel, 10).toString())
                );
                if (objeto2.mtd_guardar()) {
                    JOptionPane.showMessageDialog(null, "Registro: " + objeto2.getInMED_idInterno() + " Guardado Exitosamente");
                    mtd_limpieza();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione una Fila");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al Guardar Datos: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btn_BlabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BlabActionPerformed
        // TODO add your handling code here:
        if (objeto.mtd_buscar()) {
            txt_lab.setText(objeto.getInMED_nombComer());
        }
    }//GEN-LAST:event_btn_BlabActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Blab;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab_regisMedInv;
    private javax.swing.JTextField txt_cantidad;
    private org.jdesktop.swingx.JXDatePicker txt_fechaIngreso;
    private org.jdesktop.swingx.JXDatePicker txt_fechaVence;
    private javax.swing.JTextField txt_lab;
    private javax.swing.JTextField txt_loteFab;
    private javax.swing.JComboBox<String> txt_loteInt;
    private javax.swing.JTextField txt_nombComer;
    private javax.swing.JComboBox<String> txt_present;
    private javax.swing.JTextField txt_princAct;
    private javax.swing.JTextField txt_unitDosis;
    // End of variables declaration//GEN-END:variables
}
