/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Formularios;

import java.awt.HeadlessException;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diego
 */
public class Frm_consultaMEDinventarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form Frm_consultaMEDinventarios
     */
    public Frm_consultaMEDinventarios() {
        initComponents();
        mtd_encabezado();
        mtd_cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_idInterno = new javax.swing.JTextField();
        txt_nombComer = new javax.swing.JTextField();
        txt_princAct = new javax.swing.JTextField();
        txt_lab = new javax.swing.JTextField();
        txt_present = new javax.swing.JComboBox<>();
        txt_unitDos = new javax.swing.JTextField();
        txt_fechaIngreso = new org.jdesktop.swingx.JXDatePicker();
        txt_fechaVence = new org.jdesktop.swingx.JXDatePicker();
        txt_loteInt = new javax.swing.JComboBox<>();
        txt_loteFab = new javax.swing.JTextField();
        txt_stock = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_consultaMEDinventarios = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1280, 680));
        setPreferredSize(new java.awt.Dimension(1280, 680));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Stock de Medicamentos");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setText("ID interno :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setText("N. Comercial :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setText("P. Activo :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setText("Laboratorio :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setText("Presentación :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setText("Unidades/Dosis :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel9.setText("F. Ingreso :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel10.setText("F. Vencimiento :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel11.setText("Lote Interno :");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel12.setText("Lote Fabricante :");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel13.setText("Stock :");

        txt_idInterno.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        txt_nombComer.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        txt_princAct.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        txt_lab.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        txt_present.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_present.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Seleccione---", "Tabletas/Cápsulas", "Ampollas", "Frasco/Jarabe", "Tubo/Crema", "Sachet/Sobre", "Dispositivo/Inhalador", " " }));

        txt_unitDos.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        txt_fechaIngreso.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        txt_fechaVence.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        txt_loteInt.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_loteInt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Seleccione---", "Analgésicos/Antiinflamatorios", "Antibióticos", "Gastrointestinales", "Probióticos", "Respiratorios/Antihistamínicos", "Misceláneos" }));

        txt_loteFab.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        txt_stock.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        tab_consultaMEDinventarios.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tab_consultaMEDinventarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tab_consultaMEDinventarios);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton1.setText("Editar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton2.setText("Actualizar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton4.setText("Buscar");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(531, 531, 531)
                        .addComponent(jLabel2)
                        .addGap(0, 526, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_fechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(txt_fechaVence, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(txt_loteInt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_present, 0, 1, Short.MAX_VALUE)
                                    .addComponent(txt_lab)
                                    .addComponent(txt_princAct)
                                    .addComponent(txt_nombComer)
                                    .addComponent(txt_idInterno)
                                    .addComponent(txt_unitDos)
                                    .addComponent(txt_loteFab)
                                    .addComponent(txt_stock)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_idInterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_nombComer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_princAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_lab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_present, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_unitDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_fechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_fechaVence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_loteInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_loteFab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txt_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(0, 67, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DefaultTableModel modelo;
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
    Clases.Cls_registroInMED_V_1_3_1 objeto = new Clases.Cls_registroInMED_V_1_3_1();

    private void mtd_cargarTabla() {
        Clases.Cls_consultaMEDinventario.mtd_cargarDatosA_Modelo((DefaultTableModel) tab_consultaMEDinventarios.getModel());

        try {
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tab_consultaMEDinventarios.getModel();
            java.util.Date hoy = new java.util.Date();

            java.util.Calendar calLimite = java.util.Calendar.getInstance();
            calLimite.setTime(hoy);
            calLimite.add(java.util.Calendar.MONTH, 3);
            java.util.Date fechaLimite3Meses = calLimite.getTime();

            for (int i = 0; i < modelo.getRowCount(); i++) {
                Object valorFecha = modelo.getValueAt(i, 7);
                Object idInterno = modelo.getValueAt(i, 0);

                if (valorFecha != null && !valorFecha.toString().trim().isEmpty()) {
                    String strFecha = valorFecha.toString().trim();
                    java.util.Date fechaVence = null;

                    if (strFecha.contains("-")) {
                        fechaVence = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(strFecha);
                    } else {
                        fechaVence = sdf.parse(strFecha);
                    }

                    if (fechaVence != null) {
                        if (fechaVence.before(hoy)) {
                            javax.swing.JOptionPane.showMessageDialog(null, "Registro : " + idInterno + " Vencido");
                        } else if (fechaVence.before(fechaLimite3Meses)) {
                            javax.swing.JOptionPane.showMessageDialog(null, "Registro : " + idInterno + " Cercano a Vencer");
                        }
                    }
                }
            }
        } catch (HeadlessException | ParseException e) {
        }

        tab_consultaMEDinventarios.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                if (isSelected) {
                    return c;
                }

                try {
                    Object valorFecha = table.getValueAt(row, 7);

                    if (valorFecha != null && !valorFecha.toString().trim().isEmpty()) {
                        String strFecha = valorFecha.toString().trim();
                        java.util.Date fechaVence = null;

                        try {
                            if (strFecha.contains("-")) {
                                fechaVence = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(strFecha);
                            } else {
                                fechaVence = sdf.parse(strFecha);
                            }
                        } catch (ParseException e) {
                            try {
                                fechaVence = sdf.parse(strFecha);
                            } catch (StringIndexOutOfBoundsException ex) {
                            }
                        }

                        if (fechaVence != null) {
                            java.util.Date hoy = new java.util.Date();

                            java.util.Calendar calLimiteAnuncio = java.util.Calendar.getInstance();
                            calLimiteAnuncio.setTime(hoy);
                            calLimiteAnuncio.add(java.util.Calendar.MONTH, 3);
                            java.util.Date fechaLimite3Meses = calLimiteAnuncio.getTime();

                            if (fechaVence.before(hoy)) {
                                c.setBackground(new java.awt.Color(255, 200, 200));
                                c.setForeground(java.awt.Color.RED);
                            } else if (fechaVence.before(fechaLimite3Meses)) {
                                c.setBackground(new java.awt.Color(255, 255, 180));
                                c.setForeground(new java.awt.Color(130, 100, 0));
                            } else {
                                c.setBackground(java.awt.Color.WHITE);
                                c.setForeground(java.awt.Color.BLACK);
                            }
                        } else {
                            c.setBackground(java.awt.Color.WHITE);
                            c.setForeground(java.awt.Color.BLACK);
                        }
                    } else {
                        c.setBackground(java.awt.Color.WHITE);
                        c.setForeground(java.awt.Color.BLACK);
                    }
                } catch (ParseException e) {
                    c.setBackground(java.awt.Color.WHITE);
                    c.setForeground(java.awt.Color.BLACK);
                }
                return c;
            }
        });
    }

    private void mtd_encabezado() {
        String titulos[] = {"ID", "N.Comercial", "P.Activo", "Laboratorio", "Presentación", "Unidades/Dosis", "F. Ingreso", "F. Vence", "Lote Int.", "Lote Fab", "Stock"};
        modelo = new DefaultTableModel(null, titulos);
        tab_consultaMEDinventarios.setModel(modelo);
    }

    private boolean mtd_duplicado() {
        boolean duplicado = false;
        for (int i = 0; i < tab_consultaMEDinventarios.getRowCount(); i++) {
            if (txt_idInterno.getText().equals(tab_consultaMEDinventarios.getValueAt(i, 0).toString())) {
                duplicado = true;
                break;
            }
        }
        return duplicado;
    }

    private void mtd_limpieza() {
        txt_idInterno.setText("");
        txt_nombComer.setText("");
        txt_princAct.setText("");
        txt_lab.setText("");
        txt_present.setSelectedIndex(0);
        txt_unitDos.setText("");
        txt_fechaIngreso.setDate(null);
        txt_fechaVence.setDate(null);
        txt_loteInt.setSelectedIndex(0);
        txt_loteFab.setText("");
        txt_stock.setText("");
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int filaSel = tab_consultaMEDinventarios.getSelectedRow();
        try {
            if (filaSel != -1) {
                txt_idInterno.setText(tab_consultaMEDinventarios.getValueAt(filaSel, 0).toString());
                txt_nombComer.setText(tab_consultaMEDinventarios.getValueAt(filaSel, 1).toString());
                txt_princAct.setText(tab_consultaMEDinventarios.getValueAt(filaSel, 2).toString());
                txt_lab.setText(tab_consultaMEDinventarios.getValueAt(filaSel, 3).toString());
                txt_present.setSelectedItem(tab_consultaMEDinventarios.getValueAt(filaSel, 4).toString());
                txt_unitDos.setText(tab_consultaMEDinventarios.getValueAt(filaSel, 5).toString());

                java.text.SimpleDateFormat sdfISO = new java.text.SimpleDateFormat("yyyy-MM-dd");
                String strFechaIngreso = tab_consultaMEDinventarios.getValueAt(filaSel, 6).toString();
                String strFechaVence = tab_consultaMEDinventarios.getValueAt(filaSel, 7).toString();

                try {
                    txt_fechaIngreso.setDate(sdf.parse(strFechaIngreso));
                } catch (ParseException e) {
                    txt_fechaIngreso.setDate(sdfISO.parse(strFechaIngreso));
                }

                try {
                    txt_fechaVence.setDate(sdf.parse(strFechaVence));
                } catch (ParseException e) {
                    txt_fechaVence.setDate(sdfISO.parse(strFechaVence));
                }

                txt_loteInt.setSelectedItem(tab_consultaMEDinventarios.getValueAt(filaSel, 8).toString());
                txt_loteFab.setText(tab_consultaMEDinventarios.getValueAt(filaSel, 9).toString());
                txt_stock.setText(tab_consultaMEDinventarios.getValueAt(filaSel, 10).toString());

            } else {
                JOptionPane.showMessageDialog(null, "Por favor, seleccione una fila de la tabla.");
            }
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Error en el Formato de Fecha: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int filaSelec = tab_consultaMEDinventarios.getSelectedRow();
        if (filaSelec != -1) {
            int opcion = javax.swing.JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar este registro?");

            if (opcion == 0) {
                if (objeto.mtd_eliminar() == true) {
                    modelo = (DefaultTableModel) tab_consultaMEDinventarios.getModel();
                    String idEliminado = tab_consultaMEDinventarios.getValueAt(filaSelec, 0).toString();
                    modelo.removeRow(filaSelec);
                    javax.swing.JOptionPane.showMessageDialog(null, "Registro: " + idEliminado + " eliminado correctamente");
                    mtd_limpieza();
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Por favor Seleccione una Fila");
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int filaSel = tab_consultaMEDinventarios.getSelectedRow();
        try {
            if (txt_nombComer.getText().trim().isEmpty()) {
                txt_nombComer.requestFocus();
                throw new IllegalArgumentException("Ingrese el Nombre Comercial");
            }
            if (txt_princAct.getText().trim().isEmpty()) {
                txt_princAct.requestFocus();
                throw new IllegalArgumentException("Ingrese el Principio Activo");
            }
            if (txt_lab.getText().trim().isEmpty()) {
                txt_lab.requestFocus();
                throw new IllegalArgumentException("Ingrese el Laboratorio de Origen");
            }
            if (txt_present.getSelectedIndex() == 0) {
                txt_present.requestFocus();
                throw new IllegalArgumentException("Seleccione el Tipo de Presentación");
            }
            if (txt_unitDos.getText().trim().isEmpty()) {
                txt_unitDos.requestFocus();
                throw new IllegalArgumentException("Ingrese las Unidades/Dosis");
            }
            if (txt_fechaIngreso.getDate() == null) {
                txt_fechaIngreso.requestFocus();
                throw new IllegalArgumentException("Ingrese la Fecha de Ingreso");
            }
            if (txt_fechaVence.getDate() == null) {
                txt_fechaVence.requestFocus();
                throw new IllegalArgumentException("Ingrese la Fecha de Vencimiento");
            }
            if (txt_loteInt.getSelectedIndex() == 0) {
                txt_loteInt.requestFocus();
                throw new IllegalArgumentException("Seleccione el Lote Destino");
            }
            if (txt_loteFab.getText().trim().isEmpty()) {
                txt_loteFab.requestFocus();
                throw new IllegalArgumentException("Ingrese el Lote del Fabricante");
            }
            if (txt_stock.getText().trim().isEmpty()) {
                txt_stock.requestFocus();
                throw new IllegalArgumentException("Ingrese la cantidad");
            }
            if (filaSel != -1) {
                String idExistente = tab_consultaMEDinventarios.getValueAt(filaSel, 0).toString();

                tab_consultaMEDinventarios.setValueAt(idExistente, filaSel, 0);
                tab_consultaMEDinventarios.setValueAt(txt_nombComer.getText(), filaSel, 1);
                tab_consultaMEDinventarios.setValueAt(txt_princAct.getText(), filaSel, 2);
                tab_consultaMEDinventarios.setValueAt(txt_lab.getText(), filaSel, 3);
                tab_consultaMEDinventarios.setValueAt(txt_present.getSelectedItem(), filaSel, 4);
                tab_consultaMEDinventarios.setValueAt(txt_unitDos.getText(), filaSel, 5);
                tab_consultaMEDinventarios.setValueAt(sdf.format(txt_fechaIngreso.getDate()), filaSel, 6);
                tab_consultaMEDinventarios.setValueAt(sdf.format(txt_fechaVence.getDate()), filaSel, 7);
                tab_consultaMEDinventarios.setValueAt(txt_loteInt.getSelectedItem(), filaSel, 8);
                tab_consultaMEDinventarios.setValueAt(txt_loteFab.getText(), filaSel, 9);
                tab_consultaMEDinventarios.setValueAt(String.valueOf(txt_stock.getText()), filaSel, 10);

                objeto.setInMED_idInterno(idExistente);
                objeto.setInMED_nombComer(txt_nombComer.getText());
                objeto.setInMED_prinAct(txt_princAct.getText());
                objeto.setInMED_lab(txt_lab.getText());
                objeto.setInMED_present(txt_present.getSelectedItem().toString());
                objeto.setInMED_unitDosis(txt_unitDos.getText());
                objeto.setInMED_fechaIngreso(txt_fechaIngreso.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate());
                objeto.setInMED_fechaVence(txt_fechaVence.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate());
                objeto.setInMed_loteInt(txt_loteInt.getSelectedItem().toString());
                objeto.setInMed_loteFab(txt_loteFab.getText());
                objeto.setInMed_cant(Double.parseDouble(txt_stock.getText().trim()));

                if (objeto.mtd_guardar() == true) {
                    JOptionPane.showMessageDialog(null, "Registro :" + idExistente + " Actualizado Correctamente");
                    mtd_limpieza();
                }

            } else {
                java.time.LocalDate localFechaIngreso = null;
                java.time.LocalDate localFechaVence = null;

                if (txt_fechaIngreso.getDate() != null) {
                    localFechaIngreso = txt_fechaIngreso.getDate().toInstant()
                            .atZone(java.time.ZoneId.systemDefault()).toLocalDate();
                }
                if (txt_fechaVence.getDate() != null) {
                    localFechaVence = txt_fechaVence.getDate().toInstant()
                            .atZone(java.time.ZoneId.systemDefault()).toLocalDate();
                }

                Double cantDouble = 0.0;
                try {
                    cantDouble = Double.parseDouble(txt_stock.getText().trim());
                } catch (NumberFormatException e) {
                    throw new IllegalArgumentException("La cantidad de stock debe ser un número decimal válido.");
                }

                Clases.Cls_registroInMED_V_1_3_1 objeto1 = new Clases.Cls_registroInMED_V_1_3_1(
                        txt_nombComer.getText(),
                        txt_princAct.getText(),
                        txt_lab.getText(),
                        txt_present.getSelectedItem().toString(),
                        txt_unitDos.getText(),
                        localFechaIngreso,
                        localFechaVence,
                        txt_loteInt.getSelectedItem().toString(),
                        txt_loteFab.getText(),
                        cantDouble
                );
                modelo = (DefaultTableModel) tab_consultaMEDinventarios.getModel();
                Object nuevaFila[] = {
                    objeto1.getInMED_idInterno(),
                    objeto1.getInMED_nombComer(),
                    objeto1.getInMED_prinAct(),
                    objeto1.getInMED_lab(),
                    objeto1.getInMED_present(),
                    objeto1.getInMED_unitDosis(),
                    sdf.format(txt_fechaIngreso.getDate()),
                    sdf.format(txt_fechaVence.getDate()),
                    objeto1.getInMed_loteInt(),
                    objeto1.getInMed_loteFab(),
                    objeto1.getInMed_cant()
                };
                modelo.addRow(nuevaFila);
                JOptionPane.showMessageDialog(null, "Registro: " + objeto1.getInMED_idInterno() + " Cargado Correctamente");
                JOptionPane.showMessageDialog(null, "Verifique los Datos antes de Guardarlos");
                mtd_limpieza();
            }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error de Validación", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        objeto.setInMED_idInterno(txt_idInterno.getText());
        if (objeto.mtd_buscar()) {
            modelo = (DefaultTableModel) tab_consultaMEDinventarios.getModel();
            Object nuevaFila[] = {
                objeto.getInMED_idInterno(),
                objeto.getInMED_nombComer(),
                objeto.getInMED_prinAct(),
                objeto.getInMED_lab(),
                objeto.getInMED_present(),
                objeto.getInMED_unitDosis(),
                objeto.getInMED_fechaIngreso(),
                objeto.getInMED_fechaVence(),
                objeto.getInMed_loteInt(),
                objeto.getInMed_loteFab(),
                objeto.getInMed_cant()
            };
            modelo.addRow(nuevaFila);
        }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab_consultaMEDinventarios;
    private org.jdesktop.swingx.JXDatePicker txt_fechaIngreso;
    private org.jdesktop.swingx.JXDatePicker txt_fechaVence;
    private javax.swing.JTextField txt_idInterno;
    private javax.swing.JTextField txt_lab;
    private javax.swing.JTextField txt_loteFab;
    private javax.swing.JComboBox<String> txt_loteInt;
    private javax.swing.JTextField txt_nombComer;
    private javax.swing.JComboBox<String> txt_present;
    private javax.swing.JTextField txt_princAct;
    private javax.swing.JTextField txt_stock;
    private javax.swing.JTextField txt_unitDos;
    // End of variables declaration//GEN-END:variables
}
