/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Formularios;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diego
 */
public class Frm_registroPacientes_V1_3_1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Frm_registroPacientes_V1_3_1
     */
    public Frm_registroPacientes_V1_3_1() {
        initComponents();
        mtd_encabezado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_CiPasaporte = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_apellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_genero = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_fechaNacimiento = new org.jdesktop.swingx.JXDatePicker();
        jLabel7 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_observaciones = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_tipoPaciente = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_registroPacientes = new javax.swing.JTable();

        setBackground(new java.awt.Color(245, 247, 248));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(1280, 680));
        setPreferredSize(new java.awt.Dimension(1280, 680));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 150, 136));
        jLabel2.setText("Registro de Pacientes");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(66, 66, 66));
        jLabel3.setText("CI/Pasaporte :");

        txt_CiPasaporte.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_CiPasaporte.setForeground(new java.awt.Color(66, 66, 66));
        txt_CiPasaporte.setMaximumSize(new java.awt.Dimension(150, 25));
        txt_CiPasaporte.setMinimumSize(new java.awt.Dimension(150, 25));
        txt_CiPasaporte.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(66, 66, 66));
        jLabel1.setText("Apellidos :");

        txt_apellidos.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_apellidos.setForeground(new java.awt.Color(66, 66, 66));
        txt_apellidos.setMaximumSize(new java.awt.Dimension(150, 25));
        txt_apellidos.setMinimumSize(new java.awt.Dimension(150, 25));
        txt_apellidos.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(66, 66, 66));
        jLabel4.setText("Nombre :");

        txt_nombre.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(66, 66, 66));
        txt_nombre.setMaximumSize(new java.awt.Dimension(150, 25));
        txt_nombre.setMinimumSize(new java.awt.Dimension(150, 25));
        txt_nombre.setPreferredSize(new java.awt.Dimension(150, 25));
        txt_nombre.addActionListener(this::txt_nombreActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(66, 66, 66));
        jLabel5.setText("Género :");

        txt_genero.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_genero.setForeground(new java.awt.Color(66, 66, 66));
        txt_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Seleccione---", "Masculino", "Femenino", "No especificar" }));
        txt_genero.setMaximumSize(new java.awt.Dimension(150, 25));
        txt_genero.setMinimumSize(new java.awt.Dimension(150, 25));
        txt_genero.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(66, 66, 66));
        jLabel6.setText("Fecha de Nacimiento :");

        txt_fechaNacimiento.setForeground(new java.awt.Color(66, 66, 66));
        txt_fechaNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(66, 66, 66));
        jLabel7.setText("Teléfono :");

        txt_telefono.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_telefono.setForeground(new java.awt.Color(66, 66, 66));
        txt_telefono.setMaximumSize(new java.awt.Dimension(150, 25));
        txt_telefono.setMinimumSize(new java.awt.Dimension(150, 25));
        txt_telefono.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(66, 66, 66));
        jLabel8.setText("Correo :");

        txt_correo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_correo.setForeground(new java.awt.Color(66, 66, 66));
        txt_correo.setMaximumSize(new java.awt.Dimension(150, 25));
        txt_correo.setMinimumSize(new java.awt.Dimension(150, 25));
        txt_correo.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(66, 66, 66));
        jLabel9.setText("Observaciones :");

        txt_observaciones.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_observaciones.setForeground(new java.awt.Color(66, 66, 66));
        txt_observaciones.setMaximumSize(new java.awt.Dimension(150, 25));
        txt_observaciones.setMinimumSize(new java.awt.Dimension(150, 25));
        txt_observaciones.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(66, 66, 66));
        jLabel10.setText("Tipo de Paciente");

        txt_tipoPaciente.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_tipoPaciente.setForeground(new java.awt.Color(66, 66, 66));
        txt_tipoPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Seleccione---", "Regular ", "Frecuente" }));
        txt_tipoPaciente.setMaximumSize(new java.awt.Dimension(150, 25));
        txt_tipoPaciente.setMinimumSize(new java.awt.Dimension(150, 25));
        txt_tipoPaciente.setPreferredSize(new java.awt.Dimension(150, 25));

        jButton1.setBackground(new java.awt.Color(0, 150, 136));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_Fondos/more.png"))); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(0, 150, 136));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_Fondos/edit.png"))); // NOI18N
        jButton2.setText("Editar ");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setBackground(new java.awt.Color(0, 150, 136));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_Fondos/bin.png"))); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton6.setBackground(new java.awt.Color(0, 150, 136));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_Fondos/sav (1).png"))); // NOI18N
        jButton6.setText("Guardar");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        tab_registroPacientes.setBackground(new java.awt.Color(255, 255, 255));
        tab_registroPacientes.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tab_registroPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tab_registroPacientes.setSelectionBackground(new java.awt.Color(137, 190, 190));
        jScrollPane1.setViewportView(tab_registroPacientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(533, 533, 533))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_CiPasaporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_apellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_genero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_fechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_correo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_observaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_tipoPaciente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 939, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_CiPasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_observaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_tipoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DefaultTableModel modelo;
    java.text.SimpleDateFormat formatoFecha = new java.text.SimpleDateFormat("dd/MM/yyyy");

    private void mtd_encabezado() {
        String titulos[] = {"ID", "CI/Pasaporte", "Apellidos", "Nombres", "Género", "Fecha de Nacimiento", "Teléfono", "E-Mail", "Observaciones", "Tipo de Paciente"};
        modelo = new DefaultTableModel(null, titulos);
        tab_registroPacientes.setModel(modelo);
    }

    private boolean mtd_duplicado() {
        boolean duplicado = false;
        for (int i = 0; i < tab_registroPacientes.getRowCount(); i++) {
            if (txt_CiPasaporte.getText().equals(tab_registroPacientes.getValueAt(i, 1).toString())) {
                duplicado = true;
                break;
            }
        }
        return duplicado;
    }

    private void mtd_limpieza() {
        txt_CiPasaporte.setText("");
        txt_apellidos.setText("");
        txt_nombre.setText("");
        txt_genero.setSelectedIndex(0);
        txt_fechaNacimiento.setDate(null);
        txt_telefono.setText("");
        txt_correo.setText("");
        txt_observaciones.setText("");
        txt_tipoPaciente.setSelectedIndex(0);
    }

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int filaSel = tab_registroPacientes.getSelectedRow();
        try {
            if (filaSel != -1) {
                Clases.Cls_registroPacientesV_3_1 objeto = new Clases.Cls_registroPacientesV_3_1(
                        tab_registroPacientes.getValueAt(filaSel, 0).toString(),
                        tab_registroPacientes.getValueAt(filaSel, 1).toString(),
                        tab_registroPacientes.getValueAt(filaSel, 2).toString(),
                        tab_registroPacientes.getValueAt(filaSel, 3).toString(),
                        tab_registroPacientes.getValueAt(filaSel, 4).toString(),
                        tab_registroPacientes.getValueAt(filaSel, 5).toString(),
                        tab_registroPacientes.getValueAt(filaSel, 6).toString(),
                        tab_registroPacientes.getValueAt(filaSel, 7).toString(),
                        tab_registroPacientes.getValueAt(filaSel, 8).toString(),
                        tab_registroPacientes.getValueAt(filaSel, 9).toString()
                );
                if (objeto.mtd_guardar()) {
                    JOptionPane.showMessageDialog(null, "Registro: " + objeto.getPcs_idInterno() + " Guardado Exitosamente");
                    mtd_limpieza();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione una Fila");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al Guardar Datos: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selecFila = tab_registroPacientes.getSelectedRow();
        try {
            if (txt_CiPasaporte.getText().trim().isEmpty()) {
                txt_CiPasaporte.requestFocus();
                throw new IllegalArgumentException("Ingrese el CI/Pasaporte del Paciente");
            }
            if (txt_apellidos.getText().trim().isEmpty()) {
                txt_apellidos.requestFocus();
                throw new IllegalArgumentException("Ingrese los Apellidos del Paciente");
            }
            if (txt_nombre.getText().trim().isEmpty()) {
                txt_nombre.requestFocus();
                throw new IllegalArgumentException("Ingrese los Nombres del Paciente");
            }
            if (txt_genero.getSelectedIndex() == 0) {
                txt_genero.requestFocus();
                throw new IllegalArgumentException("Ingrese el Género del Paciente");
            }
            if (txt_fechaNacimiento.getDate() == null) {
                txt_fechaNacimiento.requestFocus();
                throw new IllegalArgumentException("Ingrese la Fecha de Nacimiento del Paciente");
            }
            if (txt_telefono.getText().trim().isEmpty()) {
                txt_telefono.requestFocus();
                throw new IllegalArgumentException("Ingrese el Número de Contacto del Paciente");
            }
            if (txt_tipoPaciente.getSelectedIndex() == 0) {
                txt_tipoPaciente.requestFocus();
                throw new IllegalArgumentException("Ingrese el Tipo de Paciente");
            }

            if (selecFila != -1) {
                String idExistente = tab_registroPacientes.getValueAt(selecFila, 0).toString();

                tab_registroPacientes.setValueAt(idExistente, selecFila, 0);
                tab_registroPacientes.setValueAt(txt_CiPasaporte.getText(), selecFila, 1);
                tab_registroPacientes.setValueAt(txt_apellidos.getText(), selecFila, 2);
                tab_registroPacientes.setValueAt(txt_nombre.getText(), selecFila, 3);
                tab_registroPacientes.setValueAt(txt_genero.getSelectedItem().toString(), selecFila, 4);
                tab_registroPacientes.setValueAt(formatoFecha.format(txt_fechaNacimiento.getDate()), selecFila, 5);
                tab_registroPacientes.setValueAt(txt_telefono.getText(), selecFila, 6);
                tab_registroPacientes.setValueAt(txt_correo.getText(), selecFila, 7);
                tab_registroPacientes.setValueAt(txt_observaciones.getText(), selecFila, 8);
                tab_registroPacientes.setValueAt(txt_tipoPaciente.getSelectedItem().toString(), selecFila, 9);
                JOptionPane.showMessageDialog(null, "Registro Actualizado Correctamente");
                mtd_limpieza();
            } else {
                if (mtd_duplicado() == false) {
                    Clases.Cls_registroPacientesV_3_1 objeto = new Clases.Cls_registroPacientesV_3_1(txt_CiPasaporte.getText().trim(), txt_apellidos.getText().trim(), txt_nombre.getText().trim(), txt_genero.getSelectedItem().toString(), formatoFecha.format(txt_fechaNacimiento.getDate()), txt_telefono.getText().trim(), txt_correo.getText().trim(), txt_observaciones.getText().trim(), txt_tipoPaciente.getSelectedItem().toString());
                    modelo = (DefaultTableModel) tab_registroPacientes.getModel();
                    String nuevaFila[] = {objeto.getPcs_idInterno(), objeto.getPcs_CiPasaporte(), objeto.getPcs_apellidos(), objeto.getPcs_nombres(), objeto.getPcs_genero(), objeto.getPcs_fechaNacimiento(), objeto.getPcs_telefono(), objeto.getPcs_correo(), objeto.getPcs_observa(), objeto.getPcs_tipoPaciente()};
                    modelo.addRow(nuevaFila);
                    JOptionPane.showMessageDialog(null, "Registro :" + objeto.getPcs_idInterno() + " Cargado Correctamente");
                    JOptionPane.showMessageDialog(null, "Verifique los Datos antes de Guardarlos");
                    mtd_limpieza();
                }
            }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, "Campos Incompletos");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error inesperado :" + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int filaSel = tab_registroPacientes.getSelectedRow();
        try {
            if (filaSel != -1) {
                txt_CiPasaporte.setText(tab_registroPacientes.getValueAt(filaSel, 1).toString());
                txt_apellidos.setText(tab_registroPacientes.getValueAt(filaSel, 2).toString());
                txt_nombre.setText(tab_registroPacientes.getValueAt(filaSel, 3).toString());
                txt_genero.setSelectedItem(tab_registroPacientes.getValueAt(filaSel, 4));
                txt_fechaNacimiento.setDate(formatoFecha.parse(tab_registroPacientes.getValueAt(filaSel, 5).toString()));
                txt_telefono.setText(tab_registroPacientes.getValueAt(filaSel, 6).toString());
                txt_correo.setText(tab_registroPacientes.getValueAt(filaSel, 7).toString());
                txt_observaciones.setText(tab_registroPacientes.getValueAt(filaSel, 8).toString());
                txt_tipoPaciente.setSelectedItem(tab_registroPacientes.getValueAt(filaSel, 9));
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione una Fila");
            }
        } catch (java.text.ParseException e) {
            JOptionPane.showMessageDialog(null, "Error en el Foprmate de Fecha dd/mm/yyyy");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, "Error Desconocido :" + e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int filaSelec = tab_registroPacientes.getSelectedRow();
        if (filaSelec != -1) {
            int opcion = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar este registro?");

            if (opcion == 0) {
                modelo = (DefaultTableModel) tab_registroPacientes.getModel();
                String idEliminado = tab_registroPacientes.getValueAt(filaSelec, 0).toString();
                modelo.removeRow(filaSelec);
                JOptionPane.showMessageDialog(null, "Registro: " + idEliminado + " eliminado correctamente");
                mtd_limpieza();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor Seleccione una Fila");
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab_registroPacientes;
    private javax.swing.JTextField txt_CiPasaporte;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_correo;
    private org.jdesktop.swingx.JXDatePicker txt_fechaNacimiento;
    private javax.swing.JComboBox<String> txt_genero;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_observaciones;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JComboBox<String> txt_tipoPaciente;
    // End of variables declaration//GEN-END:variables
}
