/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Formularios;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diego
 */
public class Frm_consultaPacientes_V1_3_1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Frm_consultaPacientes_V1_3_1
     */
    public Frm_consultaPacientes_V1_3_1() {
        initComponents();
        mtd_encabezado();
        mtd_cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_idInterno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_CiPasaporte = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_apellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_nombres = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_genero = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_observa = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_fechaNacimiento = new org.jdesktop.swingx.JXDatePicker();
        txt_tipoPaciente = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab_consultaPacientes = new javax.swing.JTable();

        setBackground(new java.awt.Color(245, 247, 248));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(1280, 680));
        setPreferredSize(new java.awt.Dimension(1280, 680));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 150, 136));
        jLabel2.setText("Base de Datos");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(66, 66, 66));
        jLabel3.setText("ID Interno :");

        txt_idInterno.setEditable(false);
        txt_idInterno.setForeground(new java.awt.Color(66, 66, 66));
        txt_idInterno.setMaximumSize(new java.awt.Dimension(150, 25));
        txt_idInterno.setMinimumSize(new java.awt.Dimension(150, 25));
        txt_idInterno.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(66, 66, 66));
        jLabel1.setText("CI/Pasaporte :");

        txt_CiPasaporte.setForeground(new java.awt.Color(66, 66, 66));
        txt_CiPasaporte.setMaximumSize(new java.awt.Dimension(150, 25));
        txt_CiPasaporte.setMinimumSize(new java.awt.Dimension(150, 25));
        txt_CiPasaporte.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(66, 66, 66));
        jLabel4.setText("Apellidos :");

        txt_apellidos.setForeground(new java.awt.Color(66, 66, 66));
        txt_apellidos.setMaximumSize(new java.awt.Dimension(150, 25));
        txt_apellidos.setMinimumSize(new java.awt.Dimension(150, 25));
        txt_apellidos.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(66, 66, 66));
        jLabel5.setText("Nombres :");

        txt_nombres.setForeground(new java.awt.Color(66, 66, 66));
        txt_nombres.setMaximumSize(new java.awt.Dimension(150, 25));
        txt_nombres.setMinimumSize(new java.awt.Dimension(150, 25));
        txt_nombres.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(66, 66, 66));
        jLabel6.setText("Género :");

        txt_genero.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_genero.setForeground(new java.awt.Color(66, 66, 66));
        txt_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Seleccione---", "Masculino", "Femenino", "No especificar" }));
        txt_genero.setMaximumSize(new java.awt.Dimension(150, 25));
        txt_genero.setMinimumSize(new java.awt.Dimension(150, 25));
        txt_genero.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(66, 66, 66));
        jLabel7.setText("Teléfono :");

        txt_telefono.setForeground(new java.awt.Color(66, 66, 66));
        txt_telefono.setMaximumSize(new java.awt.Dimension(150, 25));
        txt_telefono.setMinimumSize(new java.awt.Dimension(150, 25));
        txt_telefono.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(66, 66, 66));
        jLabel8.setText("E-Mail :");

        txt_correo.setForeground(new java.awt.Color(66, 66, 66));
        txt_correo.setMaximumSize(new java.awt.Dimension(150, 25));
        txt_correo.setMinimumSize(new java.awt.Dimension(150, 25));
        txt_correo.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(66, 66, 66));
        jLabel9.setText("Observaciones :");

        jScrollPane1.setForeground(new java.awt.Color(66, 66, 66));

        txt_observa.setColumns(20);
        txt_observa.setRows(5);
        txt_observa.setMaximumSize(new java.awt.Dimension(150, 25));
        txt_observa.setMinimumSize(new java.awt.Dimension(150, 25));
        txt_observa.setPreferredSize(new java.awt.Dimension(150, 25));
        jScrollPane1.setViewportView(txt_observa);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(66, 66, 66));
        jLabel10.setText("Tipo de Paciente :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(66, 66, 66));
        jLabel11.setText("Fecha de Nacimiento :");

        txt_fechaNacimiento.setForeground(new java.awt.Color(66, 66, 66));
        txt_fechaNacimiento.setMaximumSize(new java.awt.Dimension(150, 25));
        txt_fechaNacimiento.setMinimumSize(new java.awt.Dimension(150, 25));
        txt_fechaNacimiento.setPreferredSize(new java.awt.Dimension(150, 25));

        txt_tipoPaciente.setForeground(new java.awt.Color(66, 66, 66));
        txt_tipoPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Seleccione---", "Regular ", "Frecuente" }));
        txt_tipoPaciente.setMaximumSize(new java.awt.Dimension(150, 25));
        txt_tipoPaciente.setMinimumSize(new java.awt.Dimension(150, 25));
        txt_tipoPaciente.setPreferredSize(new java.awt.Dimension(150, 25));

        jButton1.setBackground(new java.awt.Color(0, 150, 136));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_Fondos/edit.png"))); // NOI18N
        jButton1.setText("Editar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(0, 150, 136));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_Fondos/bin.png"))); // NOI18N
        jButton2.setText("Eliminar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setBackground(new java.awt.Color(0, 150, 136));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_Fondos/search.png"))); // NOI18N
        jButton3.setText("Buscar");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setBackground(new java.awt.Color(0, 150, 136));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_Fondos/more.png"))); // NOI18N
        jButton4.setText("Actualizar");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        tab_consultaPacientes.setBackground(new java.awt.Color(255, 255, 255));
        tab_consultaPacientes.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tab_consultaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tab_consultaPacientes.setSelectionBackground(new java.awt.Color(137, 190, 190));
        jScrollPane2.setViewportView(tab_consultaPacientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(584, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(565, 565, 565))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7)
                                .addComponent(jLabel11)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_idInterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_CiPasaporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_apellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_nombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_genero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_fechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_correo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_tipoPaciente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_idInterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_CiPasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(34, 34, 34)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_tipoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton4)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(0, 60, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DefaultTableModel modelo;
    java.text.SimpleDateFormat formatoFecha = new java.text.SimpleDateFormat("dd/MM/yyyy");

    private void mtd_encabezado() {
        String titulos[] = {"ID", "CI/Pasaporte", "Apellidos", "Nombres", "Género", "Fecha de Nacimiento", "Teléfono", "E-Mail", "Observaciones", "Tipo de Paciente"};
        modelo = new DefaultTableModel(null, titulos);
        tab_consultaPacientes.setModel(modelo);
    }

    private boolean mtd_duplicado() {
        boolean duplicado = false;
        for (int i = 0; i < tab_consultaPacientes.getRowCount(); i++) {
            if (txt_CiPasaporte.getText().equals(tab_consultaPacientes.getValueAt(i, 1).toString())) {
                duplicado = true;
                break;
            }
        }
        return duplicado;
    }

    private void mtd_limpieza() {
        txt_idInterno.setText("");
        txt_CiPasaporte.setText("");
        txt_apellidos.setText("");
        txt_nombres.setText("");
        txt_genero.setSelectedIndex(0);
        txt_fechaNacimiento.setDate(null);
        txt_telefono.setText("");
        txt_correo.setText("");
        txt_observa.setText("");
        txt_tipoPaciente.setSelectedIndex(0);
    }

    private void mtd_cargarTabla() {
        Clases.Cls_consultaPacientes_V_1_3_1.mtd_cargarDatosA_Modelo((DefaultTableModel) tab_consultaPacientes.getModel());
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int filaSel = tab_consultaPacientes.getSelectedRow();
        try {
            if (filaSel != -1) {
                txt_idInterno.setText(tab_consultaPacientes.getValueAt(filaSel, 0).toString());
                txt_CiPasaporte.setText(tab_consultaPacientes.getValueAt(filaSel, 1).toString());
                txt_apellidos.setText(tab_consultaPacientes.getValueAt(filaSel, 2).toString());
                txt_nombres.setText(tab_consultaPacientes.getValueAt(filaSel, 3).toString());
                txt_genero.setSelectedItem(tab_consultaPacientes.getValueAt(filaSel, 4).toString().trim());
                txt_fechaNacimiento.setDate(formatoFecha.parse(tab_consultaPacientes.getValueAt(filaSel, 5).toString()));
                txt_telefono.setText(tab_consultaPacientes.getValueAt(filaSel, 6).toString());
                txt_correo.setText(tab_consultaPacientes.getValueAt(filaSel, 7).toString());
                txt_observa.setText(tab_consultaPacientes.getValueAt(filaSel, 8).toString());
                txt_tipoPaciente.setSelectedItem(tab_consultaPacientes.getValueAt(filaSel, 9).toString().trim());
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione una fila");
            }
        } catch (java.text.ParseException e) {
            JOptionPane.showMessageDialog(null, "Error en el Formato de Fecha dd/mm/yyyy");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, "Error Inesperado :" + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Clases.Cls_registroPacientesV_3_1 objeto = new Clases.Cls_registroPacientesV_3_1();
        int filaSelec = tab_consultaPacientes.getSelectedRow();
        if (filaSelec != -1) {
            int opcion = javax.swing.JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar este registro?");

            if (opcion == 0) {
                if (objeto.mtd_eliminar() == true) {
                    modelo = (DefaultTableModel) tab_consultaPacientes.getModel();
                    String idEliminado = tab_consultaPacientes.getValueAt(filaSelec, 0).toString();
                    modelo.removeRow(filaSelec);
                    javax.swing.JOptionPane.showMessageDialog(null, "Registro: " + idEliminado + " eliminado correctamente");
                    mtd_limpieza();
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Por favor Seleccione una Fila");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Clases.Cls_registroPacientesV_3_1 objeto = new Clases.Cls_registroPacientesV_3_1();

        if (objeto.mtd_buscar()) {
            modelo = (DefaultTableModel) tab_consultaPacientes.getModel();
            String nuevaFila[] = {objeto.getPcs_idInterno(), objeto.getPcs_CiPasaporte(), objeto.getPcs_apellidos(), objeto.getPcs_nombres(), objeto.getPcs_genero(), objeto.getPcs_fechaNacimiento(), objeto.getPcs_telefono(), objeto.getPcs_correo(), objeto.getPcs_observa(), objeto.getPcs_tipoPaciente()};
            modelo.addRow(nuevaFila);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int selecFila = tab_consultaPacientes.getSelectedRow();
        try {
            if (txt_CiPasaporte.getText().trim().isEmpty()) {
                txt_CiPasaporte.requestFocus();
                throw new IllegalArgumentException("Ingrese el CI/Pasaporte del Paciente");
            }
            if (txt_apellidos.getText().trim().isEmpty()) {
                txt_apellidos.requestFocus();
                throw new IllegalArgumentException("Ingrese los Apellidos del Paciente");
            }
            if (txt_nombres.getText().trim().isEmpty()) {
                txt_nombres.requestFocus();
                throw new IllegalArgumentException("Ingrese los Nombres del Paciente");
            }
            if (txt_genero.getSelectedIndex() == 0) {
                txt_genero.requestFocus();
                throw new IllegalArgumentException("Ingrese el Género del Paciente");
            }
            if (txt_fechaNacimiento.getDate() == null) {
                txt_fechaNacimiento.requestFocus();
                throw new IllegalArgumentException("Ingrese la Fecha de Nacimiento del Paciente");
            }
            if (txt_telefono.getText().trim().isEmpty()) {
                txt_telefono.requestFocus();
                throw new IllegalArgumentException("Ingrese el Número de Contacto del Paciente");
            }
            if (txt_tipoPaciente.getSelectedIndex() == 0) {
                txt_tipoPaciente.requestFocus();
                throw new IllegalArgumentException("Ingrese el Tipo de Paciente");
            }

            if (selecFila != -1) {

                String idExistente = tab_consultaPacientes.getValueAt(selecFila, 0).toString();
                Clases.Cls_registroPacientesV_3_1 objetoAct = new Clases.Cls_registroPacientesV_3_1(idExistente, txt_CiPasaporte.getText().trim(), txt_apellidos.getText().trim(), txt_nombres.getText().trim(), txt_genero.getSelectedItem().toString(), formatoFecha.format(txt_fechaNacimiento.getDate()), txt_telefono.getText().trim(), txt_correo.getText().trim(), txt_observa.getText().trim(), txt_tipoPaciente.getSelectedItem().toString());

                tab_consultaPacientes.setValueAt(idExistente, selecFila, 0);
                tab_consultaPacientes.setValueAt(txt_CiPasaporte.getText(), selecFila, 1);
                tab_consultaPacientes.setValueAt(txt_apellidos.getText(), selecFila, 2);
                tab_consultaPacientes.setValueAt(txt_nombres.getText(), selecFila, 3);
                tab_consultaPacientes.setValueAt(txt_genero.getSelectedItem().toString(), selecFila, 4);
                tab_consultaPacientes.setValueAt(formatoFecha.format(txt_fechaNacimiento.getDate()), selecFila, 5);
                tab_consultaPacientes.setValueAt(txt_telefono.getText(), selecFila, 6);
                tab_consultaPacientes.setValueAt(txt_correo.getText(), selecFila, 7);
                tab_consultaPacientes.setValueAt(txt_observa.getText(), selecFila, 8);
                tab_consultaPacientes.setValueAt(txt_tipoPaciente.getSelectedItem().toString(), selecFila, 9);

                if (objetoAct.mtd_guardar()) {
                    JOptionPane.showMessageDialog(null, "Registro : "+objetoAct.getPcs_idInterno()+ " Actualizado Correctamente");
                    mtd_limpieza();
                }
            } else {
                if (mtd_duplicado() == false) {
                    Clases.Cls_registroPacientesV_3_1 objeto = new Clases.Cls_registroPacientesV_3_1(txt_CiPasaporte.getText().trim(), txt_apellidos.getText().trim(), txt_nombres.getText().trim(), txt_genero.getSelectedItem().toString(), formatoFecha.format(txt_fechaNacimiento.getDate()), txt_telefono.getText().trim(), txt_correo.getText().trim(), txt_observa.getText().trim(), txt_tipoPaciente.getSelectedItem().toString());
                    modelo = (DefaultTableModel) tab_consultaPacientes.getModel();
                    String nuevaFila[] = {txt_idInterno.getText(), objeto.getPcs_CiPasaporte(), objeto.getPcs_apellidos(), objeto.getPcs_nombres(), objeto.getPcs_genero(), objeto.getPcs_fechaNacimiento(), objeto.getPcs_telefono(), objeto.getPcs_correo(), objeto.getPcs_observa(), objeto.getPcs_tipoPaciente()};
                    modelo.addRow(nuevaFila);
                    mtd_limpieza();
                }
            }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, "Campos Incompletos");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error inesperado :" + e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tab_consultaPacientes;
    private javax.swing.JTextField txt_CiPasaporte;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_correo;
    private org.jdesktop.swingx.JXDatePicker txt_fechaNacimiento;
    private javax.swing.JComboBox<String> txt_genero;
    private javax.swing.JTextField txt_idInterno;
    private javax.swing.JTextField txt_nombres;
    private javax.swing.JTextArea txt_observa;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JComboBox<String> txt_tipoPaciente;
    // End of variables declaration//GEN-END:variables
}
